In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mnist-dataset-digit-recognizer/mnist_submission.csv
/kaggle/input/mnist-dataset-digit-recognizer/__results__.html
/kaggle/input/mnist-dataset-digit-recognizer/__output__.json
/kaggle/input/mnist-dataset-digit-recognizer/custom.css


In [2]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: l

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


Reshaping the data

In [4]:
x_train = x_train.reshape((x_train.shape[0]),x_train.shape[1],x_train.shape[2],1)
x_test = x_test.reshape((x_test.shape[0]),x_test.shape[1],x_test.shape[2],1)

In [5]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


Normalizing the pixel values

In [6]:
x_train = x_train/255
x_test = x_test/255

In [7]:
print(x_train)
print(x_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [8]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [9]:
model = Sequential()

In [10]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))

In [11]:
model.add(MaxPool2D(2,2))

**adding fully connected layer**

In [12]:
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [13]:
#output layer
model.add(Dense(10,activation='softmax'))

In [14]:
#compiling model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [15]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 27s 14ms/step - loss: 0.1488 - accuracy: 0.9558
Epoch 2/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0524 - accuracy: 0.9834
Epoch 3/10
1875/1875 [==============================] - 25s 14ms/step - loss: 0.0331 - accuracy: 0.9900
Epoch 4/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0226 - accuracy: 0.9930
Epoch 5/10
1875/1875 [==============================] - 26s 14ms/step - loss: 0.0157 - accuracy: 0.9949
Epoch 6/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0119 - accuracy: 0.9960
Epoch 7/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0084 - accuracy: 0.9972
Epoch 8/10
1875/1875 [==============================] - 26s 14ms/step - loss: 0.0070 - accuracy: 0.9977
Epoch 9/10
1875/1875 [==============================] - 26s 14ms/step - loss: 0.0054 - accuracy: 0.9984
Epoch 10/10
1875/1875 [==============================] - 25s 14m

In [16]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 2s 5ms/step - loss: 0.0579 - accuracy: 0.9864


[0.05787655711174011, 0.9864000082015991]